# Generated by Django 2.2 on 2019-04-23 06:03

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=blog.models.TinyIntegerField(db_index=True, default=0, verbose_name='性别 0保密 1男 2女'),
        ),
    ]
