# Generated by Django 2.2 on 2019-04-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190423_1403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='comments',
        ),
    ]
