# Generated by Django 2.2 on 2019-06-05 03:47

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190423_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=blog.models.TinyIntegerField(default=0, verbose_name='是否激活'),
        ),
    ]
